use reservation;

CREATE TABLE ROLE (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(20),
PRIMARY KEY (ID)
)

CREATE TABLE USER_ROLE (
USER_ID INT,
ROLE_ID INT,
FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
)

INSERT INTO ROLE VALUES (1,'ADMIN');
INSERT INTO USER_ROLE VALUES (1,1);
