CREATE DATABASE RESERVATION

USE RESERVATION

CREATE TABLE USER
(
USER_ID INT NOT NULL auto_increment,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
EMAIL VARCHAR(30),
PASSWORD VARCHAR(20),
PRIMARY KEY (USER_ID),
UNIQUE KEY (EMAIL)
)

CREATE TABLE FLIGHT
(
FLIGHT_ID INT NOT NULL AUTO_INCREMENT,
FLIGHT_NUMBER VARCHAR(20) NOT NULL,
OPERATING_AIRLINES VARCHAR(20) NOT NULL,
DEPARTURE_CITY VARCHAR(20) NOT NULL,
ARRIVAL_CITY VARCHAR(30) NOT NULL,
DATE_OF_DEPARTURE DATE NOT NULL,
ESTIMATED_DEPARTURE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY  (FLIGHT_ID)
)

CREATE TABLE PASSENGER
(
 PASSENGER_ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(256),
LAST_NAME VARCHAR(256),
MIDDLE_NAME VARCHAR(256),
EMAIL VARCHAR(100),
PHONE VARCHAR(10),
PRIMARY KEY(PASSENGER_ID)
)

CREATE TABLE RESERVATION
(
RESERVATION_ID INT NOT NULL AUTO_INCREMENT,
CHECKED_IN TINYINT(1),
NUMBER_OF_BAGS INT,
PASSENGER_ID INT,
FLIGHT_ID INT,
CREATION_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY (RESERVATION_ID),
FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE,
FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(FLIGHT_ID)
)

SELECT * FROM USER;
SELECT * FROM PASSENGER;
SELECT *FROM RESERVATION;
SELECT * FROM FLIGHT;


